insert into question values(1, 'Você está em pensando em uma Fruta?', 1);
insert into question values(2, 'Seu personagem Voa?', 0);
insert into question values(3, 'Seu personagem tem Pena?', 0);
insert into question values(4, 'Seu personagem suga Sangue?', 0);
insert into question values(5, 'Seu personagem é Domestico?', 0);
insert into question values(6, 'Seu personagem Repete Palavras?', 0);
insert into question values(7, 'Seu personagem é o Mascote do Flamengo?', 0);
insert into question values(8, 'Seu personagem tem Pelo?', 0);
insert into question values(9, 'Seu personagem é Herbívoro?', 0);
insert into question values(10, 'Seu personagem é da Fauna Brasileira?', 0);
insert into question values(11, 'Seu personagem é de Fazenda?', 0);
insert into question values(12, 'Seu personagem é pequeno?', 0);
insert into question values(13, 'Seu personagem é um animal Saltitante?', 0);
insert into question values(14, 'Seu personagem é agresssivo?', 0);
insert into question values(15, 'Seu personagem luta boxe?', 0);
insert into question values(16, 'Seu personagem é preto e branco?', 0);
insert into question values(17, 'Seu personagem tem Asiático?', 0);
insert into question values(18, 'Seu personagem é o melhor amigo do homem?', 0);
insert into question values(19, 'Seu personagem é felino?', 0);
insert into question values(20, 'Seu personagem é o da Selva?', 0);
insert into question values(21, 'Seu personagem é Aquático?', 0);
insert into question values(22, 'Seu personagem é um peixe?', 0);
insert into question values(23, 'Seu personagem é de aquario?', 0);
insert into question values(24, 'Seu personagem é agressivo?', 0);
insert into question values(25, 'Seu personagem já foi Presidente?', 0);
insert into question values(26, 'Seu personagem é da savana?', 0);
insert into question values(27, 'Seu personagem é pesado?', 0);
insert into question values(28, 'Seu personagem tem Tromba?', 0);

insert into animal values ( 1, 'Cachorro', 0 );
insert into animal values ( 2, 'Gato', 0 );
insert into animal values ( 3, 'Gavião', 0 );
insert into animal values ( 4, 'Passarinho', 0 );
insert into animal values ( 5, 'Tubarão', 0 );
insert into animal values ( 6, 'Golfinho', 0 );
insert into animal values ( 7, 'Peixe dourado', 0 );
insert into animal values ( 8, 'Cavalo', 0 );
insert into animal values ( 9, 'Pinguim', 0 );
insert into animal values ( 10, 'Elefante', 0 );
insert into animal values ( 11, 'Girafa', 0 );
insert into animal values ( 12, 'Tigre', 0 );
insert into animal values ( 13, 'Leão', 0 );
insert into animal values ( 14, 'Grilo', 0 );
insert into animal values ( 15, 'Chipanzé', 0 );
insert into animal values ( 16, 'Panda', 0 );
insert into animal values ( 17, 'Urso', 0 );
insert into animal values ( 18, 'Mosca', 0 );
insert into animal values ( 19, 'Mico', 0 );
insert into animal values ( 20, 'Papagaio', 0 );
insert into animal values ( 21, 'Tartaruga Marinha', 0 );
insert into animal values ( 22, 'Lula', 0 );
insert into animal values ( 23, 'Tatu', 0 );
insert into animal values ( 24, 'Veado', 0 );
insert into animal values ( 25, 'Zebra', 0 );
insert into animal values ( 26, 'Mosquito', 0 );
insert into animal values ( 27, 'Urubu', 0 );
insert into animal values ( 28, 'Hipopotamo', 0 );
insert into animal values ( 29, 'Cabra', 0 );
insert into animal values ( 30, 'Canguru', 0 );

insert into fruit values ( 1, 'Morango', 1 );
insert into fruit values ( 2, 'Laranja', 1 );
insert into fruit values ( 3, 'Banana', 1 );
insert into fruit values ( 4, 'Tangerina', 1 );
insert into fruit values ( 5, 'Maçã', 1 );
insert into fruit values ( 6, 'Uva', 1 );
insert into fruit values ( 7, 'Melancia', 1 );
insert into fruit values ( 8, 'Acerola', 1 );
insert into fruit values ( 9, 'Melao', 1 );
insert into fruit values ( 10, 'Maracujá', 1 );
insert into fruit values ( 11, 'Perâ', 1 );
insert into fruit values ( 12, 'Caju', 1 );
insert into fruit values ( 13, 'Jabuticaba', 1 );
insert into fruit values ( 14, 'Cereja', 1 );
insert into fruit values ( 15, 'Mamão', 1 );
insert into fruit values ( 16, 'Manga', 1 );
insert into fruit values ( 17, 'Coco', 1 );
insert into fruit values ( 18, 'Limão', 1 );
insert into fruit values ( 19, 'Kiwi', 1 );
insert into fruit values ( 20, 'Jaca', 1 );
insert into fruit values ( 21, 'Amora', 1 );
insert into fruit values ( 22, 'Abacate', 1 );
insert into fruit values ( 23, 'Tomate', 1 );
insert into fruit values ( 24, 'Abacaxi', 1 );
insert into fruit values ( 25, 'Graviola', 1 );
insert into fruit values ( 26, 'Pessego', 1 );
insert into fruit values ( 27, 'Caqui', 1 );
insert into fruit values ( 28, 'Ameixa', 1 );
insert into fruit values ( 29, 'Açaí', 1 );
insert into fruit values ( 30, 'Goiaba', 1 );

insert into category values(1, 'Animal', 0);
insert into category values(2, 'Fruta', 1);

